events {}

http {
    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /api/ {
            proxy_pass http://api-service:5002/;
        }

        location /auth/ {
            proxy_pass http://auth-service:5001/;
        }
    }
}